parameters:
  linestorm.cms.module.post.poll.class:  LineStorm\PollBundle\Component\PollComponent

services:

  linestorm.cms.module.post.component.poll:
    class: %linestorm.cms.module.post.poll.class%
    tags:
      - { name: linestorm.cms.module.post.component }
