parameters:
  linestorm.blog.module.post.poll.class:  LineStorm\PollBundle\Component\PollComponent

services:

  linestorm.blog.module.post.component.poll:
    class: %linestorm.blog.module.post.poll.class%
    arguments: [@linestorm.blog.model_manager]
    tags:
      - { name: linestorm.blog.module.post.component }
