linestorm_cms_api_poll:
    type:         rest
    prefix:       /api
    resource:     LineStorm\PollComponentBundle\Controller\Api\PollController
    name_prefix:  linestorm_cms_module_post_api_

linestorm_cms_api_poll_option:
    type:         rest
    parent:       linestorm_cms_api_poll
    resource:     LineStorm\PollComponentBundle\Controller\Api\OptionController
    name_prefix:  linestorm_cms_module_post_api_
